swagger: "2.0"
info:
  title: Transactions API MOUSSA
  version: 1.0.0
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      summary: Retrieve all transactions for the current month
      parameters:
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transactions (e.g., "2023-04" for April 2023)
          default: "2023-04"
          required: true
      responses:
        200:
          description: List of transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        400:
          description: Invalid request

    post:
      summary: Add a new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Transaction"
          required: true
      responses:
        200:
          description: Transaction successfully created
        400:
          description: Invalid request (incorrect transaction data)

  /user/transactions/{transactionId}:
    get:
      summary: Retrieve details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transaction details
          required: true
      responses:
        200:
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: Transaction not found

    put:
      summary: Modify an existing transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: query
          name: month
          type: string
          description: The month for which to modify the transaction
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Transaction"
          required: true
      responses:
        200:
          description: Transaction successfully updated
        400:
          description: Invalid request (incorrect transaction data)
        404:
          description: Transaction not found

    delete:
      summary: Delete an existing transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
      responses:
        200:
          description: Transaction successfully deleted
        404:
          description: Transaction not found

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction
      month:
        type: string
        description: The month of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Account balance after the transaction
    required:
      - date
      - description
      - amount
      - balance
  User:
    type: object
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
  Login:
    type: object
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
